// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (user_id, name, url)
VALUES (
	(SELECT id FROM users WHERE id=$1),
	$2,
	$3
)
RETURNING user_id, name, url
`

type CreateFeedParams struct {
	ID   uuid.UUID
	Name string
	Url  string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.ID, arg.Name, arg.Url)
	var i Feed
	err := row.Scan(&i.UserID, &i.Name, &i.Url)
	return i, err
}
